version: 0.2

phases:
  install:
    commands:
      - echo Installing NGINX
      - apt-get update
      - apt-get install nginx -y
  build:
    commands:
      - echo "Listing all files in the working directory:"
      - ls -la
artifacts:
  files:
    - build-output/index.html
