version: 0.2

phases:
  install:
    commands:
      - echo Installing NGINX
      - apt-get update
      - apt-get install nginx -y
  build:
    commands:
      - echo Build started on `date`
      - mkdir -p build-output
      - cp index.html build-output/index.html
artifacts:
  files:
    - build-output/index.html
